apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensearch-otel.fullname" . }}-opensearch-config
  labels:
    {{- include "opensearch-otel.labels" . | nindent 4 }}
data:
  opensearch.yml: |
    cluster.name: opensearch-otel
    node.name: opensearch-node1
    network.host: 0.0.0.0
    discovery.type: single-node

    # HTTP TLS
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: certs/opensearch.crt
    plugins.security.ssl.http.pemkey_filepath: certs/opensearch.key
    plugins.security.ssl.http.pemtrustedcas_filepath: certs/ca.crt

    # Transport TLS
    plugins.security.ssl.transport.pemcert_filepath: certs/opensearch.crt
    plugins.security.ssl.transport.pemkey_filepath: certs/opensearch.key
    plugins.security.ssl.transport.pemtrustedcas_filepath: certs/ca.crt
    plugins.security.ssl.transport.enforce_hostname_verification: false

    plugins.security.allow_unsafe_democertificates: false
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - "CN=admin,OU=opensearch-otel"
    plugins.security.nodes_dn:
      - "CN=opensearch,OU=opensearch-otel"
